In [4]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
a=np.array(60)
print(a)
print(a.ndim)
print(type(a))

60
0
<class 'numpy.ndarray'>


In [9]:
a=np.array([20,30,50])
print(a)
print(a.ndim)
print(type(a))

[20 30 50]
1
<class 'numpy.ndarray'>


In [13]:
a=np.array([[20,30,50],[60,70,80]])
print(a)
print(a.ndim)
print(type(a))

[[20 30 50]
 [60 70 80]]
2
<class 'numpy.ndarray'>


In [19]:
a=np.array([[[20,30,50],[60,70,80]],
           [[100,120,150],[200,250,300]]])
print(a)
print(a.ndim)
print(type(a))

[[[ 20  30  50]
  [ 60  70  80]]

 [[100 120 150]
  [200 250 300]]]
3
<class 'numpy.ndarray'>


In [20]:
a=[1,2,3,4]
b=[5,6,7,8,]
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [21]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [28]:
c=np.sum(a)
print(c)

10


In [29]:
d=np.sum(b)
print(d)

26


In [25]:
e=np.mean(a)
print(e)

2.5


In [27]:
f=np.mean(b)
print(f)

6.5


In [33]:
x=np.array([1,2,3,"chaithu",8+9j,True,False])
print(x)
print(type(x))            

['1' '2' '3' 'chaithu' '(8+9j)' 'True' 'False']
<class 'numpy.ndarray'>
